//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carreteras
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_carreteras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_carreteras()
        {
            this.tb_carreterasXciudades = new HashSet<tb_carreterasXciudades>();
            this.tb_tramos = new HashSet<tb_tramos>();
        }
    
        public string car_id { get; set; }
        public string car_descripcion { get; set; }
        public string cat_id { get; set; }
        public string car_km_inicio { get; set; }
        public string car_km_fin { get; set; }
        public string ciu_id { get; set; }
        public string car_finC { get; set; }
        public string car_usuario_crea { get; set; }
        public Nullable<System.DateTime> car_fecha_crea { get; set; }
        public string car_usuario_modifica { get; set; }
        public Nullable<System.DateTime> car_fecha_modifica { get; set; }
        public Nullable<bool> car_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_carreterasXciudades> tb_carreterasXciudades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_tramos> tb_tramos { get; set; }
        public virtual tb_categorias tb_categorias { get; set; }
        public virtual tb_ciudades tb_ciudades { get; set; }
        public virtual tb_usuarios tb_usuarios { get; set; }
        public virtual tb_usuarios tb_usuarios1 { get; set; }
    }
}
