//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carreteras
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_comunas
    {
        public string com_id { get; set; }
        public string com_descripcion { get; set; }
        public string com_km_inicio { get; set; }
        public string com_km_fin { get; set; }
        public string tra_id { get; set; }
        public string com_usuario_crea { get; set; }
        public Nullable<System.DateTime> com_fecha_crea { get; set; }
        public string com_usuario_modifica { get; set; }
        public Nullable<System.DateTime> com_fecha_modifica { get; set; }
        public Nullable<bool> com_estado { get; set; }
    
        public virtual tb_tramos tb_tramos { get; set; }
        public virtual tb_usuarios tb_usuarios { get; set; }
        public virtual tb_usuarios tb_usuarios1 { get; set; }
    }
}
