//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carreteras
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_carreterasXciudades
    {
        public string car_id { get; set; }
        public string ciu_id { get; set; }
        public string cc_usuario_crea { get; set; }
        public Nullable<System.DateTime> cc_fecha_crea { get; set; }
        public string cc_usuario_modifica { get; set; }
        public Nullable<System.DateTime> cc_fecha_modifica { get; set; }
        public Nullable<bool> cc_estado { get; set; }
    
        public virtual tb_carreteras tb_carreteras { get; set; }
        public virtual tb_ciudades tb_ciudades { get; set; }
        public virtual tb_usuarios tb_usuarios { get; set; }
        public virtual tb_usuarios tb_usuarios1 { get; set; }
    }
}
