//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carreteras
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pantallasXroles
    {
        public string rol_id { get; set; }
        public string pant_id { get; set; }
        public string pr_usuario_crea { get; set; }
        public Nullable<System.DateTime> pr_fecha_crea { get; set; }
        public string pr_usuario_modifica { get; set; }
        public Nullable<System.DateTime> pr_fecha_modifica { get; set; }
        public Nullable<bool> pr_estado { get; set; }
    
        public virtual tb_pantallas tb_pantallas { get; set; }
        public virtual tb_roles tb_roles { get; set; }
    }
}
