//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carreteras
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuariosXroles
    {
        public string usu_id { get; set; }
        public string rol_id { get; set; }
        public string usurol_usuario_crea { get; set; }
        public Nullable<System.DateTime> usurol_fecha_crea { get; set; }
        public string usurol_usuario_modifica { get; set; }
        public Nullable<System.DateTime> usurol_fecha_modifica { get; set; }
    
        public virtual tb_roles tb_roles { get; set; }
        public virtual tb_usuarios tb_usuarios { get; set; }
        public virtual tb_usuarios tb_usuarios1 { get; set; }
        public virtual tb_usuarios tb_usuarios2 { get; set; }
    }
}
