//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carreteras
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_usuarios()
        {
            this.tb_carreteras = new HashSet<tb_carreteras>();
            this.tb_carreteras1 = new HashSet<tb_carreteras>();
            this.tb_carreterasXciudades = new HashSet<tb_carreterasXciudades>();
            this.tb_carreterasXciudades1 = new HashSet<tb_carreterasXciudades>();
            this.tb_ciudades = new HashSet<tb_ciudades>();
            this.tb_ciudades1 = new HashSet<tb_ciudades>();
            this.tb_comunas = new HashSet<tb_comunas>();
            this.tb_comunas1 = new HashSet<tb_comunas>();
            this.tb_departamentos = new HashSet<tb_departamentos>();
            this.tb_departamentos1 = new HashSet<tb_departamentos>();
            this.tb_pantallas = new HashSet<tb_pantallas>();
            this.tb_pantallas1 = new HashSet<tb_pantallas>();
            this.tb_roles1 = new HashSet<tb_roles>();
            this.tb_roles2 = new HashSet<tb_roles>();
            this.tb_tramos = new HashSet<tb_tramos>();
            this.tb_tramos1 = new HashSet<tb_tramos>();
            this.tb_categorias = new HashSet<tb_categorias>();
            this.tb_categorias1 = new HashSet<tb_categorias>();
            this.tb_empleados1 = new HashSet<tb_empleados>();
            this.tb_empleados2 = new HashSet<tb_empleados>();
            this.tb_usuarios1 = new HashSet<tb_usuarios>();
            this.tb_usuarios11 = new HashSet<tb_usuarios>();
            this.tb_empleadosXusuarios = new HashSet<tb_empleadosXusuarios>();
            this.tb_empleadosXusuarios1 = new HashSet<tb_empleadosXusuarios>();
            this.tb_empleadosXusuarios2 = new HashSet<tb_empleadosXusuarios>();
            this.tb_usuariosXroles = new HashSet<tb_usuariosXroles>();
            this.tb_usuariosXroles1 = new HashSet<tb_usuariosXroles>();
            this.tb_usuariosXroles2 = new HashSet<tb_usuariosXroles>();
        }
    
        public string usu_id { get; set; }
        public string usu_descripcion { get; set; }
        public string usu_password { get; set; }
        public string emp_id { get; set; }
        public string rol_id { get; set; }
        public string usu_usuario_crea { get; set; }
        public Nullable<System.DateTime> usu_fecha_crea { get; set; }
        public string usu_usuario_modifica { get; set; }
        public Nullable<System.DateTime> usu_fecha_modifica { get; set; }
        public Nullable<bool> usu_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_carreteras> tb_carreteras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_carreteras> tb_carreteras1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_carreterasXciudades> tb_carreterasXciudades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_carreterasXciudades> tb_carreterasXciudades1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ciudades> tb_ciudades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ciudades> tb_ciudades1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_comunas> tb_comunas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_comunas> tb_comunas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_departamentos> tb_departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_departamentos> tb_departamentos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pantallas> tb_pantallas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_pantallas> tb_pantallas1 { get; set; }
        public virtual tb_roles tb_roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_roles> tb_roles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_roles> tb_roles2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_tramos> tb_tramos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_tramos> tb_tramos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_categorias> tb_categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_categorias> tb_categorias1 { get; set; }
        public virtual tb_empleados tb_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_empleados> tb_empleados1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_empleados> tb_empleados2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_usuarios> tb_usuarios1 { get; set; }
        public virtual tb_usuarios tb_usuarios2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_usuarios> tb_usuarios11 { get; set; }
        public virtual tb_usuarios tb_usuarios3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_empleadosXusuarios> tb_empleadosXusuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_empleadosXusuarios> tb_empleadosXusuarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_empleadosXusuarios> tb_empleadosXusuarios2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_usuariosXroles> tb_usuariosXroles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_usuariosXroles> tb_usuariosXroles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_usuariosXroles> tb_usuariosXroles2 { get; set; }
    }
}
